Fix bucket_name bucketname consistency
coralnet/pyspacer pull request #88
Opened 2024-01-24 01:16 UTC by yeelauren

Separating out into smaller PRs  :smile_cat: 

Refactor for consistency see: https://github.com/coralnet/pyspacer/blob/cb0b427b03f60bb92e2e9bdf1ccbb64e5b2230c3/spacer/storage.py#L187

https://github.com/coralnet/pyspacer/blob/cb0b427b03f60bb92e2e9bdf1ccbb64e5b2230c3/spacer/storage.py#L205

https://github.com/coralnet/pyspacer/blob/cb0b427b03f60bb92e2e9bdf1ccbb64e5b2230c3/spacer/messages.py#L25

2024-01-24 01:22 UTC, yeelauren commented
Additionally a new change from #85 ircc will also need to be changed  https://github.com/coralnet/pyspacer/blob/478a8f6f01d7bdc1cb7b40866d36d89b53dda314/spacer/messages.py#L71

2024-01-24 02:54 UTC, StephenChan commented
Thanks Lauren! This'll make reviewing easier.

I'm definitely onboard with making this param name consistent, but:

1. It looks like there are still a decent amount of `bucket_name` usages remaining: for example in `messages.py`, `storage.py`, `tests/test_storage.py`, `tests/utils.py`, and `README.md`.
2. Pardon my pickiness, but unless there's another reason I've overlooked (e.g. consistency with boto), I think I'd actually favor `bucket_name` over `bucketname`. The style goes better with the `storage_type` param in `DataLocation.__init__()` and `storage_factory()`; and originally there were more usages of `bucket_name` than `bucketname` (around 50 vs. 10).

2024-01-24 14:37 UTC, yeelauren commented
@StephenChan I agree that makes more sense - the latest push should address those changes !

2024-01-24 20:52 UTC, StephenChan requested changes
Thanks Lauren, looks good regarding the param naming! I reviewed the other bits of the PR.

2024-01-24 20:52 UTC, StephenChan commented on spacer/tasks.py
> -
This `getLogger` import is still needed. (This was something I worked with recently, so maybe this deletion was a merge/rebase slip-up?)

2024-01-24 20:52 UTC, StephenChan commented on spacer/storage.py
> +            raise ValueError("bucket_name must be a string for s3 storage")
This check works for me since it's related and useful.

2024-01-24 20:52 UTC, StephenChan commented on spacer/tasks.py
> +    check_rowcols(msg.rowcols, img)
`check_rowcols()` was replaced with `check_extract_inputs()` in PR #70. So don't need this line.

2024-01-24 20:52 UTC, StephenChan commented on spacer/tasks.py
> +        raise TypeError("features object must have a store method")
These two type checks (well, instance/attribute checks to be exact) aren't that related to the rest of the PR.

They're also not really needed in my opinion - I think in Python, type checks don't hurt individually but they can add up to clutter the codebase somewhat. I know Oscar had several such checks in the codebase here and there, but in general I wasn't really keen on adding more. Sometimes they're a good idea with recent API changes (like PR #62 which admittedly relates to the first check here), but I'd like to think that's more of a worry for apps with larger userbases than pyspacer's.

2024-01-25 20:02 UTC, StephenChan approved these changes
Thanks!

2024-01-25 20:03 UTC, merged